#!/bin/sh
#update the icon cache
gtk-update-icon-cache -f /usr/share/icons/hicolor

# copy the desktop file for use
( cd /usr/share/applications/hildon/ && mv conboy.inactive conboy.desktop )

# select the installation folder
if [ -f /usr/bin/X11/maemo-select-menu-location ]
	then /usr/bin/X11/maemo-select-menu-location conboy.desktop
fi
